
[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[template.environment]
  FAUNADB_SERVER_SECRET = "Your FaunaDB Server Secret"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200